print("Example\nStrings")
print("Example\"Strings")
print("Example\Strings")

phrase = ("Example Strings")
print(phrase)
print(phrase + " are fun.")

phrase = ("Example Strings")
print(phrase.lower())
print(phrase.upper())
print(phrase.isupper())
print(phrase.upper().isupper())
print(len(phrase))
print(phrase[0])
print(phrase.index("E"))
print(phrase.index("amp"))
print(phrase.replace("Strings", "Text"))
